"""Original procedural SFX, quiet and sparse. No music, no external assets.

Cue times follow storyboard.json: the opening zoom hand-off at 4.0s and the
card entrances listed in render-ui.py WINDOWS.
"""
from pathlib import Path
import numpy as np, soundfile as sf, subprocess, json

p = Path(__file__).resolve().parent
sr = 48000
end = 49.6
a = np.zeros(round(end * sr))
rng = np.random.default_rng(20260910)

cues = [
    (4.00, .34, .016, 'opening zoom in'),
    (6.40, .14, .008, 'every-minute card'),
    (10.60, .14, .008, 'how-long card'),
    (17.40, .14, .008, 'no-link card'),
    (19.00, .30, .010, 'blur in on the duration turn'),
    (23.00, .14, .009, 'peak-and-end card'),
    (26.90, .13, .008, 'two-points card'),
    (30.10, .14, .008, '682-patients card'),
    (34.30, .30, .010, 'blur in on the trial result'),
    (34.60, .14, .009, 'result card'),
    (39.70, .14, .008, 'memory-keeps card'),
    (47.10, .13, .008, 'closing card'),
]

for at, dur, gain, label in cues:
    t = np.arange(round(dur * sr)) / sr
    if 'zoom' in label or 'blur' in label:
        noise = rng.normal(size=len(t))
        v = np.convolve(noise, np.ones(25) / 25, mode='same')
        v /= max(abs(v))
        v *= np.sin(np.pi * t / dur) ** 2
    else:
        v = (np.sin(2 * np.pi * (720 * t + 180 * t * t))
             * np.exp(-t * 35) * np.minimum(t / .008, 1))
    i = round(at * sr)
    a[i:i + len(v)] += v * gain

sf.write(p / 'audio/sfx.wav', a, sr, subtype='PCM_16')
subprocess.run([
    'ffmpeg', '-y', '-v', 'error',
    '-i', str(p / 'audio/narration.wav'), '-i', str(p / 'audio/sfx.wav'),
    '-filter_complex',
    '[0:a]loudnorm=I=-16:TP=-2:LRA=9[v];'
    '[v][1:a]amix=inputs=2:normalize=0,alimiter=limit=0.94:level=false,apad=whole_dur=49.6[a]',
    '-map', '[a]', '-ar', '48000', '-t', str(end),
    str(p / 'audio/final-mix.wav')], check=True)

(p / 'sfx.json').write_text(json.dumps({
    'cues': cues,
    'rights': ('Original procedural effects generated by this script; '
               'no music, no external sound assets, nothing from a meme API.'),
}, indent=2) + '\n')
print('final-mix.wav written')
