from pathlib import Path
import json,math
p=Path(__file__).resolve().parent
D=36.333333333333336
C={'wheel':4.0,'globe':9.433333333333334,'chart':14.4,'low':16.566666666666666,'row2':17.7,'high':19.2,'meaning':22.433333333333334,'focus':24.033333333333335,'home':26.9,'value':28.566666666666666,'compare':30.6,'shop':32.233333333333334,'end':D}
def wheel(id):
 parts=[];vals=[0,10,20,30,40,50,60,65,70,80,90,100]
 for i,n in enumerate(vals):
  theta=math.radians(-90+i*30);a=theta-math.pi/12;b=theta+math.pi/12;r=294
  x1,y1=360+r*math.cos(a),360+r*math.sin(a);x2,y2=360+r*math.cos(b),360+r*math.sin(b)
  fill='#e7d9b8' if i%2==0 else '#c5cbb8'
  if n in (10,65):fill='#e7bd73'
  parts.append(f'<path d="M360 360L{x1} {y1}A{r} {r} 0 0 1 {x2} {y2}Z" fill="{fill}" stroke="#715f48" stroke-width="2"/>')
  x,y=360+231*math.cos(theta),360+231*math.sin(theta)
  parts.append(f'<text x="{x}" y="{y}" fill="#24413d" font-family="Stiles" font-size="35" text-anchor="middle" dominant-baseline="middle" transform="rotate({i*30},{x},{y})">{n}</text>')
 return '<svg viewBox="0 0 720 720" width="720" height="720"><rect x="346" y="622" width="28" height="93" rx="5" fill="#80623f" stroke="#503f2c" stroke-width="3"/><circle cx="360" cy="360" r="312" fill="#685039" stroke="#d1b688" stroke-width="8"/><g id="'+id+'">'+''.join(parts)+'</g><circle cx="360" cy="360" r="39" fill="#caa46a" stroke="#5f4e3a" stroke-width="7"/><circle cx="360" cy="360" r="14" fill="#735b3f"/><path d="M332 26H388L360 89Z" fill="#edcf8d" stroke="#5f4c36" stroke-width="5"/></svg>'
css='''@font-face{font-family:Stiles;src:url(assets/DejaVuSans-Bold.ttf)}*{box-sizing:border-box}html,body{margin:0;width:1080px;height:1920px;overflow:hidden;background:#112e30;color:#f2e6cd;font-family:Stiles,sans-serif}#root{position:relative;width:1080px;height:1920px;overflow:hidden}.scene{position:absolute;inset:0;overflow:hidden}.backdrop{position:absolute;inset:0;background-position:center;background-size:cover}.shade{position:absolute;inset:0;background:linear-gradient(180deg,rgba(9,28,29,.62),transparent 40%,rgba(7,25,28,.25))}.room{background-image:url(assets/research-room.png)}.wheel{position:absolute;left:180px;top:258px;width:720px;height:720px;filter:drop-shadow(0 13px 7px #071a2140)}.headline{position:absolute;top:194px;left:80px;right:80px;font-size:82px;line-height:1.12;letter-spacing:-2px}.small{font-size:33px;line-height:1.35}.gold{color:#e7c17d}.takeaway{position:absolute;left:80px;right:80px;top:1390px;font-size:74px;line-height:1.16;letter-spacing:-2px}.note{position:absolute;left:80px;top:470px;width:550px;padding:30px 36px;border-radius:22px;background:#efe3c7;color:#23433d;box-shadow:0 10px 32px #00151633;font-size:49px;line-height:1.2}.simple-label{position:absolute;left:80px;right:80px;top:1100px;text-align:center;font-size:47px;color:#e4d4b0}.row{position:absolute;left:105px;right:105px;height:250px;display:flex;align-items:center;justify-content:space-between}.anchor{width:230px;height:230px;display:flex;align-items:center;justify-content:center;background:#264846;border:3px solid #59736a;border-radius:50%;font-size:112px;color:#d6ddc9}.arrow{font-size:85px;color:#8da69b}.estimate{width:340px;font-size:140px;color:#efce8b;text-align:center}.labelrow{position:absolute;top:410px;left:100px;right:100px;display:flex;justify-content:space-between;font-size:35px;color:#bfccbf}.quiet{position:absolute;left:80px;right:80px;top:1490px;text-align:center;font-size:33px;color:#b7c8bb;line-height:1.4}
#s1,#s2,#s3,#s4,#s5,#s6,#r2,#low,#high,#thought,#value,#alternative{opacity:0;visibility:hidden}'''
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Anchoring — focused remake</title><style>CSS</style></head><body><div id="root" data-composition-id="anchor-remake" data-width="1080" data-height="1920" data-start="0" data-duration="DURATION" data-fps="30">
<div id="s0" class="scene"><video id="pricedTag" class="clip" style="position:absolute;width:1080px;height:1920px;object-fit:cover" src="assets/priced-hook.mp4" muted playsinline data-volume="0" data-start="0" data-duration="4.4" data-track-index="0"></video><div class="small" style="position:absolute;left:80px;top:1550px;text-shadow:0 2px 8px #000">Example prices</div></div>
<section id="s1" class="scene clip" data-start="0" data-duration="DURATION" data-track-index="1"><div class="backdrop room"></div><div class="wheel">WHEEL1</div></section>
<section id="s2" class="scene clip" data-start="0" data-duration="DURATION" data-track-index="2"><div class="backdrop" style="background-image:url(assets/globe.png)"></div><div class="shade"></div><div class="headline" style="font-size:72px">UN members<br><span class="gold">from Africa?</span></div></section>
<section id="s3" class="scene clip" data-start="0" data-duration="DURATION" data-track-index="3" style="background:#123336"><div class="backdrop room" style="opacity:.07;filter:blur(8px)"></div><div class="headline">Different starting points.</div><div class="labelrow"><span>Wheel number</span><span>Median estimate</span></div><div id="r1" class="row" style="top:570px"><div class="anchor">10</div><div class="arrow">→</div><div id="low" class="estimate">25%</div></div><div id="r2" class="row" style="top:890px"><div class="anchor">65</div><div class="arrow">→</div><div id="high" class="estimate">45%</div></div><div class="quiet">Participants’ guesses.<br>Not the correct answer.</div></section>
<section id="s4" class="scene clip" data-start="0" data-duration="DURATION" data-track-index="4"><div id="meaningRoom" class="backdrop room"></div><div id="meaningWheel" class="wheel">WHEEL2</div><div class="shade" style="opacity:.5"></div><div id="thought" class="takeaway">A starting point.<br><span class="gold">Not evidence.</span></div></section>
<section id="s5" class="scene clip" data-start="0" data-duration="DURATION" data-track-index="5"><div class="backdrop" style="background-image:url(assets/home.png)"></div><div class="shade"></div><div id="value" class="note" style="top:200px">Worth it<br>to me?</div><div id="alternative" class="note" style="top:200px">What are<br>my alternatives?</div></section>
<section id="s6" class="scene clip" data-start="0" data-duration="DURATION" data-track-index="6"><div class="backdrop" style="background-image:url(assets/shop-wide.png)"></div><div class="shade"></div><div class="takeaway" style="top:1380px;font-size:72px">A discount<br><span class="gold">≠ a good deal.</span></div></section>
<script src="assets/gsap.min.js"></script><script>
const C=CUES;const tl=gsap.timeline({paused:true});gsap.set(['#s1','#s2','#s3','#s4','#s5','#s6','#r2','#low','#high','#thought','#value','#alternative'],{autoAlpha:0});
function change(next,prev,start){tl.to(prev+' > :not(.backdrop):not(.shade):not(video)',{opacity:0,duration:.14,ease:'power1.out'},start);tl.to(next,{autoAlpha:1,duration:.28,ease:'power1.inOut'},start+.14);tl.to(prev,{autoAlpha:0,duration:.28,ease:'power1.inOut'},start+.14);}
change('#s1','#s0',C.wheel);tl.fromTo('#wheelOne',{rotation:0,svgOrigin:'360 360'},{rotation:690,svgOrigin:'360 360',duration:4.55,ease:'power2.out'},C.wheel+.14);
change('#s2','#s1',C.globe);tl.fromTo('#s2 .backdrop',{scale:1},{scale:1.025,duration:C.chart-C.globe,ease:'none'},C.globe);
change('#s3','#s2',C.chart);tl.fromTo('#low',{autoAlpha:0,y:18},{autoAlpha:1,y:0,duration:.4,ease:'power2.out'},C.low);tl.fromTo('#r2',{autoAlpha:0,y:18},{autoAlpha:1,y:0,duration:.4,ease:'power2.out'},C.row2);tl.fromTo('#high',{autoAlpha:0,y:18},{autoAlpha:1,y:0,duration:.4,ease:'power2.out'},C.high);
change('#s4','#s3',C.meaning);gsap.set('#wheelTwo',{rotation:-30,svgOrigin:'360 360'});tl.fromTo('#thought',{autoAlpha:0,y:12},{autoAlpha:1,y:0,duration:.35,ease:'power2.out'},C.focus-.25);tl.to('#meaningRoom',{filter:'blur(10px)',duration:.35},C.focus-.25);tl.to('#meaningWheel',{filter:'blur(6px)',opacity:.58,duration:.35},C.focus-.25);
change('#s5','#s4',C.home);tl.fromTo('#value',{autoAlpha:0,y:18},{autoAlpha:1,y:0,duration:.4,ease:'power2.out'},C.value);tl.to('#value',{autoAlpha:0,duration:.14},C.compare);tl.fromTo('#alternative',{autoAlpha:0,y:12},{autoAlpha:1,y:0,duration:.28,ease:'power2.out'},C.compare+.14);
change('#s6','#s5',C.shop);tl.fromTo('#s6 .backdrop',{scale:1.025},{scale:1,duration:C.end-C.shop,ease:'power1.out'},C.shop);
window.__timelines=window.__timelines||{};window.__timelines['anchor-remake']=tl;
</script></div></body></html>'''
(p/'index.html').write_text(html.replace('CSS',css).replace('DURATION',str(D)).replace('CUES',json.dumps(C)).replace('WHEEL1',wheel('wheelOne')).replace('WHEEL2',wheel('wheelTwo')))
(p/'cue-times.json').write_text(json.dumps(C,indent=2));names=['priced Agnes hook','illustrated number-wheel experiment','globe context','one simple two-row comparison','meaning and selective focus','own value and alternatives','shop landing'];starts=[0,C['wheel'],C['globe'],C['chart'],C['meaning'],C['home'],C['shop']]
(p/'storyboard.json').write_text(json.dumps({'duration':D,'unique_source_illustrations':5,'new_generated_illustrations':3,'ui_comparison_seconds':C['meaning']-C['chart'],'narration':'Exact previous approved recording, no new synthesis or speed change','phases':[{'name':n,'start':a,'end':starts[i+1] if i+1<len(starts) else D} for i,(n,a) in enumerate(zip(names,starts))],'focus':'Printed price remains sharp over blurred surroundings; later isolate one takeaway. Captions and comparison pair remain sharp. No persistent corner brand, progress bar or on-screen academic citation.'},indent=2));print('Prepared seven beats / five illustration sources / one comparison UI.')
