from pathlib import Path
import json,math,subprocess
p=Path(__file__).resolve().parent;D=math.ceil((float(subprocess.check_output(['ffprobe','-v','error','-show_entries','format=duration','-of','csv=p=0',str(p/'audio/narration.wav')]))+.3)*30)/30
C={'reading':3.05,'easy':4.13,'blank':6.06,'recognize':7.57,'experiment':9.53,'immediate':11.94,'delayed':14.01,'confidence':16.5,'confidenceText':18.53,'recall':21.19,'recallText':23.06,'correct':25.54,'correctText':26.6,'later':28.52,'laterText':28.82,'ending':33.46,'landing':36.4,'end':D};(p/'cue-times.json').write_text(json.dumps(C,indent=2))
phases=[(0,3.05,'book'),(3.05,6.06,'reading'),(6.06,9.53,'blank'),(9.53,16.5,'experiment'),(16.5,21.19,'confidence'),(21.19,25.54,'recall'),(25.54,28.52,'correct'),(28.52,33.46,'later'),(33.46,D,'recall')]
css='''@font-face{font-family:Stiles;src:url(assets/DejaVuSans-Bold.ttf)}*{box-sizing:border-box}html,body{margin:0;width:1080px;height:1920px;background:#f3eedc;color:#254b45;overflow:hidden;font-family:Stiles}#root,.scene{position:absolute;inset:0;width:1080px;height:1920px;overflow:hidden}.art{position:absolute;inset:0;background-size:cover;background-position:center;transform:scale(1.018)}.heading{position:absolute;left:90px;right:90px;top:180px;font-size:80px;line-height:1.15;letter-spacing:-2px}.small{font-size:45px;line-height:1.2;letter-spacing:-1px;margin-bottom:16px;color:#5c7568}.bottom{top:1440px}.accent{color:#886220}.scene:not(#s0),.copy{opacity:0;visibility:hidden}#openingZoom{position:absolute;inset:0;transform-origin:50% 58%;}'''
scenes=['<div id="s0" class="scene"><div id="openingZoom"><video id="bookHook" class="clip" src="assets/hook-ready.mp4" muted playsinline data-start="0" data-duration="3.6" data-track-index="0" style="width:1080px;height:1920px;object-fit:cover"></video></div></div>']
texts={1:'<div id="easy" class="heading copy">Feels easy.</div>',2:'<div id="recognize" class="heading copy" style="font-size:73px">Recognizing<br>≠ recalling.</div>',3:'<div id="immediate" class="heading copy" style="font-size:58px;top:120px"><div class="small">Right away</div>Rereading helped more.</div><div id="delayed" class="heading copy" style="font-size:58px;top:120px"><div class="small">Days later</div>Recall helped more.</div>',4:'<div id="confidenceText" class="heading copy" style="font-size:64px;top:175px;right:auto;width:540px">Confidence<br>≠ retention.</div>',5:'<div id="recallText" class="heading copy">Recall.</div>',6:'<div id="correctText" class="heading copy" style="font-size:64px;top:1540px;background:#f4eedb;padding:24px 28px;border-radius:12px">Check + correct.</div>',7:'<div id="laterText" class="heading copy" style="font-size:70px">Try again later.</div>',8:'<div id="landing" class="heading copy" style="font-size:76px">Close.<br>Recall.<br><span class="accent">Check.</span></div>'}
for i,(a,b,name) in enumerate(phases[1:],1):scenes.append(f'<section id="s{i}" class="scene clip" data-start="0" data-duration="{D}" data-track-index="{i}"><div class="art" style="background-image:url(assets/{name}.png)"></div>{texts[i]}</section>')
js='''const C=CUES;const tl=gsap.timeline({paused:true});gsap.set(['.scene:not(#s0)','.copy'],{autoAlpha:0});
function enter(a,b,t){tl.to(b+' .copy',{autoAlpha:0,duration:.12},t);tl.to(a,{autoAlpha:1,duration:.24,ease:'power1.inOut'},t+.12);tl.to(b,{autoAlpha:0,duration:.24,ease:'power1.inOut'},t+.12)}
function reveal(id,t){tl.fromTo(id,{autoAlpha:0,y:10},{autoAlpha:1,y:0,duration:.28,ease:'power2.out'},t)}
function drift(id,a,b,r=false){tl.fromTo(id+' .art',{scale:r?1.032:1.018,x:r?4:-4},{scale:r?1.018:1.032,x:r?-4:4,duration:b-a,ease:'none'},a)}
// Distinct hook punch, NOT body micro-motion:100% to105%, then return.
tl.fromTo('#openingZoom',{scale:1},{scale:1.05,duration:.38,ease:'power2.out'},.08);tl.to('#openingZoom',{scale:1,duration:.55,ease:'power1.inOut'},.75);
PHASEJS
for(const id of ['easy','recognize','immediate','confidenceText','recallText','correctText','laterText','landing'])reveal('#'+id,C[id]);
tl.to('#immediate',{autoAlpha:0,duration:.13},C.delayed);reveal('#delayed',C.delayed+.13);tl.to('#laterText',{autoAlpha:0,duration:.2},30.61);
window.__timelines=window.__timelines||{};window.__timelines.closebook=tl;'''
phasejs='\n'.join(f"enter('#s{i}','#s{i-1}',{a});drift('#s{i}',{a},{b},{str(i%2==0).lower()});" for i,(a,b,name) in enumerate(phases[1:],1))
html=f'<!doctype html><html><head><meta charset="utf-8"><title>Close the Book</title><style>{css}</style></head><body><div id="root" data-composition-id="closebook" data-width="1080" data-height="1920" data-start="0" data-duration="{D}" data-fps="30">'+''.join(scenes)+'<script src="assets/gsap.min.js"></script><script>'+js.replace('CUES',json.dumps(C)).replace('PHASEJS',phasejs)+'</script></div></body></html>'
(p/'index.html').write_text(html);(p/'storyboard.json').write_text(json.dumps({'duration':D,'generated_images':8,'used_unique_images':8,'shots':len(phases),'longest_hold':max(b-a for a,b,n in phases),'phases':[{'start':a,'end':b,'source':n,'seconds':b-a} for a,b,n in phases],'ending_reuse':'Brief callback to the exact same recall-practice artwork, not a regenerated duplicate; under7s.','style':'Cleaner flat cream teal ochre, restrained context and canonical proportions.','opening_zoom':'100→105→100%, authored separately over actual Agnes object footage'},indent=2));assert max(b-a for a,b,n in phases)<=7;print('Duration',D,'8 illustrations /9 beats /max hold',max(b-a for a,b,n in phases))
