from pathlib import Path
import json,subprocess,hashlib
from PIL import Image,ImageOps,ImageDraw
p=Path(__file__).resolve().parent;f=p/'output/awkward-silence-final.mp4';d=json.loads(subprocess.check_output(['ffprobe','-v','error','-show_format','-show_streams','-of','json',str(f)]));v=next(x for x in d['streams'] if x['codec_type']=='video');a=next(x for x in d['streams'] if x['codec_type']=='audio');q=subprocess.run(['ffmpeg','-hide_banner','-i',str(f),'-af','loudnorm=I=-16:TP=-1.5:LRA=11:print_format=json','-f','null','-'],capture_output=True,text=True);loud=json.JSONDecoder().raw_decode(q.stderr[q.stderr.rfind('{'):])[0];lines=[x for x in (p/'captions.ass').read_text().splitlines() if x.startswith('Dialogue:')];tm=lambda s:sum(float(x)*k for x,k in zip(s.split(':'),(3600,60,1)));cap=[(tm(x.split(',')[1]),tm(x.split(',')[2])) for x in lines];assert len(cap)==100 and all(b>a for a,b in cap) and all(cap[i][1]<=cap[i+1][0] for i in range(len(cap)-1));assert v['width']==1080 and v['height']==1920 and v['r_frame_rate']=='30/1' and float(d['format']['duration'])<=40
qc={'duration_seconds':float(d['format']['duration']),'width':v['width'],'height':v['height'],'fps':v['r_frame_rate'],'video_codec':v['codec_name'],'audio_codec':a['codec_name'],'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'bytes':f.stat().st_size,'loudness':loud,'caption_events':len(cap),'captions_nonoverlapping':True,'last_caption_end':cap[-1][1],'source_images':15,'provider_split':{'agent_generator':10,'agnes_ai':5}};(p/'technical-qc.json').write_text(json.dumps(qc,indent=2)+'\n');print(json.dumps(qc))
canvas=Image.new('RGB',(1100,1200),'#16232a');sc=json.loads((p/'timeline.json').read_text())['scenes']
for i,x in enumerate(sc):
 t=(x['start']+x['end'])/2;out=p/'output'/f'qc-{i:02}.jpg';subprocess.run(['ffmpeg','-y','-v','error','-ss',str(t),'-i',str(f),'-frames:v','1',str(out)],check=True);canvas.paste(ImageOps.fit(Image.open(out),(210,374)),((i%5)*220,(i//5)*400));ImageDraw.Draw(canvas).text(((i%5)*220,(i//5)*400+375),f"{i+1:02} {x['image']} {t:.2f}s",fill='white')
canvas.save('/home/user/silence-final-qc.jpg')
