from pathlib import Path
import json,math,subprocess
p=Path(__file__).resolve().parent
D=math.ceil((float(subprocess.check_output(['ffprobe','-v','error','-show_entries','format=duration','-of','csv=p=0',str(p/'audio/narration.wav')]))+.3)*30)/30
C={'cafe':4.29,'familiar':7.09,'definition':9.84,'library':11.86,'knowledge':16.52,'check':19.08,'question':22.78,'diagram':24.41,'source':25.47,'copies':26.14,'return':28.21,'original':28.21,'independent':30.85,'landing':36.4,'end':D};(p/'cue-times.json').write_text(json.dumps(C,indent=2))
html='''<!doctype html><html><head><meta charset="utf-8"><title>Familiar Is Not Verified</title><style>
@font-face{font-family:Stiles;src:url(assets/DejaVuSans-Bold.ttf)}*{box-sizing:border-box}html,body{margin:0;width:1080px;height:1920px;overflow:hidden;background:#153638;font-family:Stiles;color:#f3e6c9}#root,.scene{position:absolute;inset:0;width:1080px;height:1920px;overflow:hidden}.art{position:absolute;inset:0;background-size:cover;background-position:center;transform:scale(1.018)}.shade{position:absolute;inset:0;background:linear-gradient(180deg,#0c292b99,transparent 40%,#0c292b20 65%,#0c292b90)}.heading{position:absolute;top:185px;left:80px;right:80px;font-size:80px;line-height:1.12;letter-spacing:-2px;text-shadow:0 3px 10px #102a2d80}.gold{color:#edcc8d}#s5 .shade{background:linear-gradient(180deg,#0c292b88,transparent 42%,#0c292bb0 82%,#0c292b80)}.bottom{position:absolute;left:80px;right:80px;top:1430px;font-size:71px;line-height:1.13;letter-spacing:-2px;text-shadow:0 3px 12px #10282b90}.pill{position:absolute;left:80px;right:80px;top:180px;background:#efe3c7;color:#23463f;padding:28px 32px;border-radius:17px;font-size:53px;line-height:1.2}.post{position:absolute;top:405px;width:235px;height:285px;background:#eee1c4;border-radius:15px;box-shadow:0 14px 24px #001b2230;padding:36px}.post .dot{width:62px;height:62px;border-radius:50%;background:#537f75;margin-bottom:33px}.post .line{height:11px;background:#6d8171;margin-top:17px;border-radius:3px}.origin{position:absolute;left:255px;top:890px;width:570px;height:170px;border:3px solid #89a092;background:#294e49;border-radius:18px;display:flex;align-items:center;justify-content:center;font-size:61px}.connector{stroke:#95ab9b;stroke-width:5;fill:none}#s1,#s2,#s3,#s4,#s5,#familiar,#definition,#knowledge,#question,#origin,#lines,#copies,#original,#independent,#landing{opacity:0;visibility:hidden}
</style></head><body><div id="root" data-composition-id="familiar" data-width="1080" data-height="1920" data-start="0" data-duration="DURATION" data-fps="30">
<div id="s0" class="scene"><div class="art" style="background-image:url(assets/press.png)"></div></div>
<section id="s1" class="scene clip" data-start="0" data-duration="DURATION" data-track-index="1"><div class="art" style="background-image:url(assets/cafe.png)"></div><div class="shade"></div><div id="familiar" class="heading">Feels familiar.</div><div id="definition" class="heading">Illusory<br><span class="gold">truth.</span></div></section>
<section id="s2" class="scene clip" data-start="0" data-duration="DURATION" data-track-index="2"><div class="art" style="background-image:url(assets/library.png)"></div><div class="shade"></div><div id="knowledge" class="bottom">Knowing ≠<br><span class="gold">always using.</span></div></section>
<section id="s3" class="scene clip" data-start="0" data-duration="DURATION" data-track-index="3"><div class="art" style="background-image:url(assets/check.png)"></div><div class="shade"></div><div id="question" class="heading" style="font-size:69px">Where did the<br><span class="gold">evidence come from?</span></div></section>
<section id="s4" class="scene clip" data-start="0" data-duration="DURATION" data-track-index="4" style="background:#163b3b"><div class="heading">Three posts.</div><div class="post" style="left:100px"><div class="dot"></div><div class="line"></div><div class="line"></div><div class="line" style="width:70%"></div></div><div class="post" style="left:422px"><div class="dot"></div><div class="line"></div><div class="line"></div><div class="line" style="width:70%"></div></div><div class="post" style="left:745px"><div class="dot"></div><div class="line"></div><div class="line"></div><div class="line" style="width:70%"></div></div><svg id="lines" style="position:absolute;inset:0" viewBox="0 0 1080 1920"><path class="connector" d="M217 690V765Q217 805 300 805H540V890M540 690V890M862 690V765Q862 805 780 805H540"/></svg><div id="origin" class="origin">One source.</div><div id="copies" class="bottom">Copies ≠<br><span class="gold">confirmation.</span></div></section>
<section id="s5" class="scene clip" data-start="0" data-duration="DURATION" data-track-index="5"><div class="art" style="background-image:url(assets/check.png)"></div><div class="shade"></div><div id="original" class="pill">Find the original evidence.</div><div id="independent" class="pill">Check independent support.</div><div id="landing" class="bottom">Familiar<br><span class="gold">≠ verified.</span></div></section>
<script src="assets/gsap.min.js"></script><script>
const C=CUES;const tl=gsap.timeline({paused:true});gsap.set(['#s1','#s2','#s3','#s4','#s5','#familiar','#definition','#knowledge','#question','#origin','#lines','#copies','#original','#independent','#landing'],{autoAlpha:0});
function enter(a,b,t){tl.to(b+' > :not(.art):not(.shade):not(video)',{opacity:0,duration:.14},t);tl.to(a,{autoAlpha:1,duration:.28,ease:'power1.inOut'},t+.14);tl.to(b,{autoAlpha:0,duration:.28,ease:'power1.inOut'},t+.14)}
function reveal(id,t){tl.fromTo(id,{autoAlpha:0,y:12},{autoAlpha:1,y:0,duration:.34,ease:'power2.out'},t)}
// Barely perceptible monotonic moves, no oscillation; enough overscan to never show edges.
function drift(id,t,end,reverse=false){tl.fromTo(id+' .art',{scale:reverse?1.038:1.018,x:reverse?6:-6,y:reverse?-4:4},{scale:reverse?1.018:1.038,x:reverse?-6:6,y:reverse?4:-4,duration:end-t,ease:'none'},t)}
drift('#s0',0,C.cafe);enter('#s1','#s0',C.cafe);drift('#s1',C.cafe,C.library);reveal('#familiar',C.familiar);tl.to('#familiar',{autoAlpha:0,duration:.16},9.31);reveal('#definition',C.definition);
enter('#s2','#s1',C.library);drift('#s2',C.library,C.check,true);reveal('#knowledge',C.knowledge);
enter('#s3','#s2',C.check);drift('#s3',C.check,C.diagram);reveal('#question',C.question);
enter('#s4','#s3',C.diagram);reveal('#origin',C.source);reveal('#lines',C.source);reveal('#copies',C.copies);
enter('#s5','#s4',C.return);drift('#s5',C.return,C.end);reveal('#original',C.original+.25);tl.to('#original',{autoAlpha:0,duration:.14},C.independent);reveal('#independent',C.independent+.14);tl.to('#independent',{autoAlpha:0,duration:.2},33.4);reveal('#landing',C.landing);
window.__timelines=window.__timelines||{};window.__timelines.familiar=tl;
</script></div></body></html>'''
(p/'index.html').write_text(html.replace('DURATION',str(D)).replace('CUES',json.dumps(C)))
(p/'storyboard.json').write_text(json.dumps({'duration':D,'unique_illustrations':4,'phases':6,'micro_motion':'Each illustration hold:1.018–1.038 scale with12px horizontal and8px vertical travel, no loops, stationary captions and text. Overscan protects all edges. Same check artwork reused, not regenerated.','beats':[[0,4.29,'print workshop authored slow camera drift; Agnes unavailable503'],[4.29,11.86,'reassured cafe reader / familiarity'],[11.86,19.08,'skeptical library / knowledge neglect'],[19.08,24.41,'trace evidence / focused archive'],[24.41,28.21,'conceptual three copies linked to one source; not statistical data'],[28.21,D,'same archive art; original evidence and independent support']]},indent=2));print(D)
