from pathlib import Path
import json,math,subprocess
import soundfile as sf
p=Path(__file__).resolve().parent;w=json.loads((p/'audio/words.json').read_text())['words'];t=lambda i:round(w[i]['start']*30)/30
a,sr=sf.read(p/'audio/narration.wav');D=math.ceil((len(a)/sr+.3)*30)/30
C={'study':4.0,'question':t(26),'low':t(63),'high':t(72),'insight':t(75),'name':t(86),'ending':t(95),'fact':t(101),'guess':t(111),'landing':t(114),'duration':D}
(p/'cue-times.json').write_text(json.dumps(C,indent=2))
subprocess.run(['ffmpeg','-y','-v','error','-i',str(p/'assets/hook.mp4'),'-an','-vf','scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,fps=30,tpad=stop_mode=clone:stop_duration=0.4','-t','4.4','-c:v','libx264','-preset','fast','-crf','18','-threads','2','-pix_fmt','yuv420p',str(p/'assets/hook-ready.mp4')],check=True)
style=(p/'theme.css').read_text().replace('assets/cafe.png','assets/shop.png').replace('assets/study.png','assets/stiles.png')
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Why the First Price Changes the Next One</title><style>STYLE
#studyUI,#ending,#questionBox,#lowDot,#highDot,#insightBox,#anchorName,#stepOne,#stepTwo,#lastLine{opacity:0;visibility:hidden}.price{font-size:150px;letter-spacing:-8px;margin-top:35px;white-space:nowrap}.struck{color:#e5d6bd;text-decoration:line-through;text-decoration-thickness:8px}.intro-caption{font-size:45px;line-height:1.3;margin-top:30px}.rail{stroke:#6b8581;stroke-width:4;stroke-linecap:round}.reading{font-family:Stiles;fill:#e9dfc8}.step .value{font-size:38px}.step{padding:27px 35px}
</style></head><body><div id="root" data-composition-id="anchor" data-width="1080" data-height="1920" data-start="0" data-duration="DURATION" data-fps="30">
<div id="intro" class="scene"><video id="agnesHook" class="photo clip" data-start="0" data-duration="4.4" data-track-index="1" data-volume="0" src="assets/hook-ready.mp4" muted playsinline></video><div class="shade"></div><div class="heading"><div class="eyebrow">PRICE IS NOT THE SAME AS VALUE</div><div class="price"><span class="struck">$99</span> <span class="gold">$49</span></div><div class="intro-caption">A bargain…<br>or a starting point?</div></div><div class="foot small" style="top:1530px">Illustrative prices · not a real offer</div></div>
<div id="studyUI" class="scene bgui clip" data-start="0" data-duration="DURATION" data-track-index="2"><div class="photo ghost study-photo"></div><div class="tint"></div><div class="heading"><div class="eyebrow">THE ANCHOR NEED NOT BE RELEVANT</div><h1 style="font-size:80px">Arbitrary number.<br><span class="gold">Different estimates.</span></h1><div class="chip" style="margin-top:40px;font-size:26px">HIGHER / LOWER FIRST → THEN ESTIMATE</div></div>
<div style="position:absolute;left:80px;top:610px;font-size:32px;color:#d2ded4">Median participant estimates · not correct answers</div>
<svg style="position:absolute;left:80px;top:690px" width="920" height="420" viewBox="0 0 920 420"><g class="reading" font-size="32"><text x="15" y="35">Wheel number: 10</text><text x="15" y="225">Wheel number: 65</text></g><g class="rail"><path d="M30 110H880"/><path d="M30 300H880"/></g><g class="reading" font-size="25" opacity=".65"><text x="25" y="157">0%</text><text x="423" y="157">50%</text><text x="827" y="157">100%</text><text x="25" y="350">0%</text><text x="423" y="350">50%</text><text x="827" y="350">100%</text></g><g id="lowDot"><circle cx="242.5" cy="110" r="18" fill="#deeee6"/><text class="reading" text-anchor="middle" x="242.5" y="85" font-size="39">25%</text></g><g id="highDot"><circle cx="412.5" cy="300" r="19" fill="#ecc67f"/><text text-anchor="middle" x="412.5" y="274" fill="#ecc67f" font-size="39" font-family="Stiles">45%</text></g></svg>
<div id="questionBox" class="card darkcard" style="top:1370px"><div class="label">THE QUESTION</div><div style="font-size:37px;line-height:1.4">What share of UN members<br>were African countries?</div></div><div id="insightBox" class="card darkcard" style="top:1370px"><div class="label">THE WHEEL WAS NOT EVIDENCE</div><div style="font-size:37px;line-height:1.4">Different starting points.<br>Different group estimates.</div></div><div id="anchorName" class="chip" style="position:absolute;top:1110px;left:80px;color:#edc980;font-size:30px">THIS IS ANCHORING</div><div class="source" style="top:1680px">Historical experiment · Tversky &amp; Kahneman (1974)<br>Full 0–100% scale · group medians, not means</div></div>
<div id="ending" class="scene clip" data-start="0" data-duration="DURATION" data-track-index="3"><div class="photo study-photo" style="opacity:.72;transform:translateX(240px);mask-image:linear-gradient(to right,transparent,black 30%)"></div><div class="shade"></div><div class="heading"><div class="eyebrow">BEFORE THE SALE PAGE</div><h1 style="font-size:79px">Set your number.<br><span class="gold">Then compare.</span></h1></div><div id="stepOne" class="card step" style="top:620px;right:auto;width:590px"><div class="label">01 / YOUR REFERENCE</div><div class="value">What is it worth to me?</div></div><div id="stepTwo" class="card step darkcard" style="top:920px;right:auto;width:590px"><div class="label">02 / REAL ALTERNATIVES</div><div class="value">What else could I buy?</div></div><div id="lastLine" class="foot" style="top:1460px;font-size:41px">A big discount<br><span class="gold">is not proof of a good deal.</span></div></div>
<div id="brand" class="brand clip" data-start="0" data-duration="DURATION" data-track-index="10">STILES / PSYCHOLOGY</div><div id="progress" class="progress clip" data-start="0" data-duration="DURATION" data-track-index="11"></div>
<script src="assets/gsap.min.js"></script><script>const C=CUES;const tl=gsap.timeline({paused:true});
gsap.set(['#studyUI','#ending','#questionBox','#lowDot','#highDot','#insightBox','#anchorName','#stepOne','#stepTwo','#lastLine'],{autoAlpha:0});
function change(id,start,previous){tl.to(previous+' > :not(.photo):not(.shade):not(.tint)',{opacity:0,duration:.14,ease:'power1.out'},start);tl.to(id,{autoAlpha:1,duration:.26,ease:'power1.inOut'},start+.14);tl.to(previous,{autoAlpha:0,duration:.26,ease:'power1.inOut'},start+.14);}
tl.fromTo('#agnesHook',{scale:1},{scale:1.05,duration:.26,ease:'power2.out'},0);tl.to('#agnesHook',{scale:1,duration:.45,ease:'power2.inOut'},.26);
change('#studyUI',C.study,'#intro');
tl.fromTo('#questionBox',{y:18,autoAlpha:0},{y:0,autoAlpha:1,duration:.4,ease:'power2.out'},C.question);
tl.fromTo('#lowDot',{x:-212.5,autoAlpha:0},{x:0,autoAlpha:1,duration:.8,ease:'power2.out'},C.low);
tl.fromTo('#highDot',{x:-382.5,autoAlpha:0},{x:0,autoAlpha:1,duration:.8,ease:'power2.out'},C.high);
tl.to('#questionBox',{autoAlpha:0,duration:.14},C.insight);tl.fromTo('#insightBox',{y:15,autoAlpha:0},{y:0,autoAlpha:1,duration:.35},C.insight+.14);
tl.fromTo('#anchorName',{y:12,autoAlpha:0},{y:0,autoAlpha:1,duration:.4},C.name);
change('#ending',C.ending,'#studyUI');
tl.fromTo('#stepOne',{x:-25,autoAlpha:0},{x:0,autoAlpha:1,duration:.4,ease:'power2.out'},C.fact);
tl.fromTo('#stepTwo',{x:25,autoAlpha:0},{x:0,autoAlpha:1,duration:.4,ease:'power2.out'},C.guess);
tl.fromTo('#lastLine',{y:14,autoAlpha:0},{y:0,autoAlpha:1,duration:.4},C.landing);
tl.fromTo('#progress',{scaleX:0},{scaleX:1,duration:C.duration,ease:'none'},0);window.__timelines=window.__timelines||{};window.__timelines.anchor=tl;
</script></div></body></html>'''
(p/'index.html').write_text(html.replace('STYLE',style).replace('DURATION',str(D)).replace('CUES',json.dumps(C)))
(p/'storyboard.json').write_text(json.dumps({'duration':D,'source_illustrations':2,'generated_video_hook_seconds':4,'scenes':[{'start':0,'end':4,'visual':'Agnes tag sway + hypothetical price overlay'},{'start':4,'end':C['ending'],'visual':'One stable study UI: question, animated medians, then mechanism; semantic sub-beats change only relevant elements'},{'start':C['ending'],'end':D,'visual':'Stiles compares alternatives; two practical cards'}],'cues':C},indent=2));print(C)
