#!/usr/bin/env python3
import json
from collections import Counter
from datetime import datetime,timezone
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'calendar/2026-09-07_2026-10-06.json'
d=json.loads(p.read_text());now=datetime.now(timezone.utc)
print('# Stiles Psychology — calendar status\n')
print('Period:',d['start_date'],'through',d['end_date'],'| target:',len(d['items']),'videos\n')
for k,v in sorted(Counter(x['status'] for x in d['items']).items()):print(f'- **{k}**: {v}')
print('\n## Overdue unfinished slots\n')
late=[x for x in d['items'] if datetime.fromisoformat(x['publish_at_utc'].replace('Z','+00:00'))<now and x['status'] not in ('scheduled','published','cancelled')]
for x in late:print(f"- {x['id']}: {x['title']} — {x['status']}; manual rescheduling required")
if not late:print('None.')
print('\nA calendar entry is not a generated video. No asset is uploaded until it is ready and passes all quality gates. Exact YouTube public-upload eligibility and long-term OAuth validity still depend on Google project settings.')
print('\n## Ready inventory (already produced; do not regenerate)')
for x in d['items']:
 if x['status']=='ready':print(f"- {x['id']}: {x['title']} — {x['scheduled_at']}")
print('\n## Release alerts / holds')
for x in d['items']:
 if x.get('release_alert') or x.get('publication_hold'):print(f"- {x['id']}: {x.get('release_alert') or 'Publication hold'}")
print('\nLast authenticated YouTube sync:',d.get('last_remote_sync_at','not recorded'))

# Owner requested a durable link registry: Cloudinary master plus YouTube per produced item.
rows=[x for x in d['items'] if x.get('asset_url') or x.get('youtube_url')]
out=['# Produced videos — links registry','','Generated by tools/calendar-report.py from the calendar, which stays the source of truth. A scheduled YouTube link stays private until its publish time. A missing link means that step genuinely did not happen.','','| ID | Prague slot | Title | Status | Cloudinary master | YouTube |','|---|---|---|---|---|---|']
for x in rows:
 c=x.get('asset_url');y=x.get('youtube_url')
 out.append(f"| {x['id']} | {x['scheduled_at']} | {x['title']} | {x['status']} | {'[master mp4]('+c+')' if c else '—'} | {'['+y.rsplit('=',1)[-1]+']('+y+')' if y else '—'} |")
(p.parent/'VIDEO-LINKS.md').write_text('\n'.join(out)+'\n')
print('\nLink registry written to calendar/VIDEO-LINKS.md')
