from pathlib import Path
import numpy as np,soundfile as sf,subprocess,json
p=Path(__file__).resolve().parent;sr=48000;end=68.2;a=np.zeros(round(end*sr));rng=np.random.default_rng(20260909)
cues=[(.06,.36,.020,'opening zoom in'),(.53,.25,.010,'opening zoom out'),(12.5,.18,.010,'polished desk glint'),(39.3,.10,.012,'specific instruction'),(46.0,.12,.010,'rough sentence'),(64.4,.12,.009,'closing question')]
for at,dur,gain,label in cues:
 t=np.arange(round(dur*sr))/sr
 if 'zoom' in label:
  noise=rng.normal(size=len(t));v=np.convolve(noise,np.ones(25)/25,mode='same');v/=max(abs(v));v*=np.sin(np.pi*t/dur)**2
 else:v=np.sin(2*np.pi*(720*t+180*t*t))*np.exp(-t*35)*np.minimum(t/.008,1)
 i=round(at*sr);a[i:i+len(v)]+=v*gain
sf.write(p/'audio/sfx.wav',a,sr,subtype='PCM_16')
subprocess.run(['ffmpeg','-y','-v','error','-i',str(p/'audio/narration.wav'),'-i',str(p/'audio/sfx.wav'),'-filter_complex','[0:a]loudnorm=I=-16:TP=-2:LRA=9[v];[v][1:a]amix=inputs=2:normalize=0,alimiter=limit=0.94:level=false[a]','-map','[a]','-ar','48000','-t',str(end),str(p/'audio/final-mix.wav')],check=True)
(p/'sfx.json').write_text(json.dumps({'cues':cues,'rights':'Original procedural effects generated by this script; no music or external sound assets'},indent=2))
